USE [master]
GO

/****** Object:  Database [dem]    Script Date: 22.06.2022 8:22:39 ******/
CREATE DATABASE [dem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dem] SET ARITHABORT OFF 
GO

ALTER DATABASE [dem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dem] SET  MULTI_USER 
GO

ALTER DATABASE [dem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [dem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dem] SET  READ_WRITE 
GO


