//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventActivity = new HashSet<EventActivity>();
        }
    
        public int Id { get; set; }
        public string Logo { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdCity { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdDirection { get; set; }
        public Nullable<System.TimeSpan> StartTImeEvent { get; set; }
        public Nullable<System.TimeSpan> EndTimeEvent { get; set; }
    
        public virtual City City { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventActivity> EventActivity { get; set; }
    }
}
